### ISSUE TITLE
IRC notifications from Travis CI aren't working

### ISSUE THREAD

**Issue by tripu** [w3c/node-w3capi#16]
OK, this is an insignificant issue. But I'm intrigued, and I want to have a second pair of eyes on it.

I added recently [config to send messages to an IRC channel](https://github.com/w3c/node-w3capi/blob/master/.travis.yml#L7-L11) after builds on Travis. [Builds are OK](https://travis-ci.org/w3c/node-w3capi/builds/117452829), but we're receiving no messages on that channel. The configuration is very similar to what we have in other projects (Specberus, Echidna).

What am I missing?

#travis

**Comment by deniak** [comment]
The channel was configured to refuse outside message. I removed that mode. Should be ok now.

**Comment by tripu** [comment]
Thanks, @deniak. I thought I would see *something* on the Travis log: a mention of the notification, an error returned from our IRC server, something.
