### ISSUE TITLE
Explore ways to leverage API cache(s)

### ISSUE THREAD

**Issue by tripu** [w3c/node-w3capi#30]
To optimise API usage and save on total time to load.

**Comment by tripu** [comment]
(Note to self: read https://mariadb.com/kb/en/the-mariadb-library/query-cache/ )

**Comment by gosko** [comment]
I think the API server already has a cache built in, so may be no need for more caching?

**Comment by tripu** [comment]
Is that so, @jean-gui, @vivienlacourba?

And if so, do you think there's room for more caching at another level?

On my side, I might explore caching on the client, eg via a Service Worker.

**Comment by Kiriii2** [comment]
Yeah

**Comment by deniak** [comment]
Closing as we can now benefit from the Cloudflare cache
