### ISSUE TITLE
Cannot install specberus with yarn

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/node-w3capi#64]
Specberus installation with yarn fails, as `node-w3capi` (npm version), a dependency of `specberus` does not support Node 14. 

`npm i` gives the warning:
```
npm WARN notsup Unsupported engine for node-w3capi@1.8.0: wanted: {"node":"8 || 10","npm":"6"} (current: {"node":"14.14.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: node-w3capi@1.8.0
```

but yarn errors in install due to this.
```
error node-w3capi@1.8.0: The engine "node" is incompatible with this module. Expected version "8 || 10". Got "14.14.0"
error Found incompatible module.
```

Releasing the latest node-w3capi to npm would fix the issue.

**Comment by deniak** [comment]
@sidvishnoi thanks for the report. We just released node-w3capi 1.9.0.
